//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUCEAdmin.sv1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctResult_ettOftbl_TaiKhoan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FunctResult_ettOftbl_TaiKhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private HUCEAdmin.sv1.EnumErrCode ErrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HUCEAdmin.sv1.tbl_TaiKhoan DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public HUCEAdmin.sv1.EnumErrCode ErrCode {
            get {
                return this.ErrCodeField;
            }
            set {
                if ((this.ErrCodeField.Equals(value) != true)) {
                    this.ErrCodeField = value;
                    this.RaisePropertyChanged("ErrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrDesc {
            get {
                return this.ErrDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrDescField, value) != true)) {
                    this.ErrDescField = value;
                    this.RaisePropertyChanged("ErrDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public HUCEAdmin.sv1.tbl_TaiKhoan Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_TaiKhoan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class tbl_TaiKhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaiKhoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        private System.Nullable<bool> Is_LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateByField;
        
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastEditByField;
        
        private System.Nullable<System.DateTime> LastEditDateField;
        
        private System.Nullable<byte> Is_DeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeleteByField;
        
        private System.Nullable<System.DateTime> DeleteDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaNhomQuyenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TaiKhoan {
            get {
                return this.TaiKhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.TaiKhoanField, value) != true)) {
                    this.TaiKhoanField = value;
                    this.RaisePropertyChanged("TaiKhoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<bool> Is_Login {
            get {
                return this.Is_LoginField;
            }
            set {
                if ((this.Is_LoginField.Equals(value) != true)) {
                    this.Is_LoginField = value;
                    this.RaisePropertyChanged("Is_Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CreateBy {
            get {
                return this.CreateByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateByField, value) != true)) {
                    this.CreateByField = value;
                    this.RaisePropertyChanged("CreateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LastEditBy {
            get {
                return this.LastEditByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastEditByField, value) != true)) {
                    this.LastEditByField = value;
                    this.RaisePropertyChanged("LastEditBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> LastEditDate {
            get {
                return this.LastEditDateField;
            }
            set {
                if ((this.LastEditDateField.Equals(value) != true)) {
                    this.LastEditDateField = value;
                    this.RaisePropertyChanged("LastEditDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<byte> Is_Delete {
            get {
                return this.Is_DeleteField;
            }
            set {
                if ((this.Is_DeleteField.Equals(value) != true)) {
                    this.Is_DeleteField = value;
                    this.RaisePropertyChanged("Is_Delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string DeleteBy {
            get {
                return this.DeleteByField;
            }
            set {
                if ((object.ReferenceEquals(this.DeleteByField, value) != true)) {
                    this.DeleteByField = value;
                    this.RaisePropertyChanged("DeleteBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.DeleteDateField;
            }
            set {
                if ((this.DeleteDateField.Equals(value) != true)) {
                    this.DeleteDateField = value;
                    this.RaisePropertyChanged("DeleteDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string MaNhomQuyen {
            get {
                return this.MaNhomQuyenField;
            }
            set {
                if ((object.ReferenceEquals(this.MaNhomQuyenField, value) != true)) {
                    this.MaNhomQuyenField = value;
                    this.RaisePropertyChanged("MaNhomQuyen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumErrCode", Namespace="http://tempuri.org/")]
    public enum EnumErrCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidInput = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYetLogin = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyData = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExistentUnique = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctResult_ettOfListOftbl_TaiKhoan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FunctResult_ettOfListOftbl_TaiKhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private HUCEAdmin.sv1.EnumErrCode ErrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HUCEAdmin.sv1.ArrayOfTbl_TaiKhoan DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public HUCEAdmin.sv1.EnumErrCode ErrCode {
            get {
                return this.ErrCodeField;
            }
            set {
                if ((this.ErrCodeField.Equals(value) != true)) {
                    this.ErrCodeField = value;
                    this.RaisePropertyChanged("ErrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrDesc {
            get {
                return this.ErrDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrDescField, value) != true)) {
                    this.ErrDescField = value;
                    this.RaisePropertyChanged("ErrDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public HUCEAdmin.sv1.ArrayOfTbl_TaiKhoan Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfTbl_TaiKhoan", Namespace="http://tempuri.org/", ItemName="tbl_TaiKhoan")]
    [System.SerializableAttribute()]
    public class ArrayOfTbl_TaiKhoan : System.Collections.Generic.List<HUCEAdmin.sv1.tbl_TaiKhoan> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumDataType", Namespace="http://tempuri.org/")]
    public enum EnumDataType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ma = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaiKhoan = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctResult_ettOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FunctResult_ettOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private HUCEAdmin.sv1.EnumErrCode ErrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrDescField;
        
        private bool DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public HUCEAdmin.sv1.EnumErrCode ErrCode {
            get {
                return this.ErrCodeField;
            }
            set {
                if ((this.ErrCodeField.Equals(value) != true)) {
                    this.ErrCodeField = value;
                    this.RaisePropertyChanged("ErrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrDesc {
            get {
                return this.ErrDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrDescField, value) != true)) {
                    this.ErrDescField = value;
                    this.RaisePropertyChanged("ErrDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sv1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name tk from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        HUCEAdmin.sv1.LoginResponse Login(HUCEAdmin.sv1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.LoginResponse> LoginAsync(HUCEAdmin.sv1.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name tk from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        HUCEAdmin.sv1.LogoutResponse Logout(HUCEAdmin.sv1.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.LogoutResponse> LogoutAsync(HUCEAdmin.sv1.LogoutRequest request);
        
        // CODEGEN: Generating message contract since element name tk from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        HUCEAdmin.sv1.GetDataResponse GetData(HUCEAdmin.sv1.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.GetDataResponse> GetDataAsync(HUCEAdmin.sv1.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name tk from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataByID", ReplyAction="*")]
        HUCEAdmin.sv1.GetDataByIDResponse GetDataByID(HUCEAdmin.sv1.GetDataByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataByID", ReplyAction="*")]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.GetDataByIDResponse> GetDataByIDAsync(HUCEAdmin.sv1.GetDataByIDRequest request);
        
        // CODEGEN: Generating message contract since element name tk from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search_Paging", ReplyAction="*")]
        HUCEAdmin.sv1.Search_PagingResponse Search_Paging(HUCEAdmin.sv1.Search_PagingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search_Paging", ReplyAction="*")]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.Search_PagingResponse> Search_PagingAsync(HUCEAdmin.sv1.Search_PagingRequest request);
        
        // CODEGEN: Generating message contract since element name tk from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        HUCEAdmin.sv1.CreateResponse Create(HUCEAdmin.sv1.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.CreateResponse> CreateAsync(HUCEAdmin.sv1.CreateRequest request);
        
        // CODEGEN: Generating message contract since element name tk from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        HUCEAdmin.sv1.EditResponse Edit(HUCEAdmin.sv1.EditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.EditResponse> EditAsync(HUCEAdmin.sv1.EditRequest request);
        
        // CODEGEN: Generating message contract since element name tk from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        HUCEAdmin.sv1.DeleteResponse Delete(HUCEAdmin.sv1.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.DeleteResponse> DeleteAsync(HUCEAdmin.sv1.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(HUCEAdmin.sv1.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tk;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mk;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string tk, string mk) {
            this.tk = tk;
            this.mk = mk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(HUCEAdmin.sv1.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(HUCEAdmin.sv1.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tk;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string tk) {
            this.tk = tk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(HUCEAdmin.sv1.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan LogoutResult;
        
        public LogoutResponseBody() {
        }
        
        public LogoutResponseBody(HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(HUCEAdmin.sv1.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tk;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string tk) {
            this.tk = tk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(HUCEAdmin.sv1.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HUCEAdmin.sv1.FunctResult_ettOfListOftbl_TaiKhoan GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(HUCEAdmin.sv1.FunctResult_ettOfListOftbl_TaiKhoan GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByID", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.GetDataByIDRequestBody Body;
        
        public GetDataByIDRequest() {
        }
        
        public GetDataByIDRequest(HUCEAdmin.sv1.GetDataByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tk;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        public GetDataByIDRequestBody() {
        }
        
        public GetDataByIDRequestBody(string tk, string id) {
            this.tk = tk;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.GetDataByIDResponseBody Body;
        
        public GetDataByIDResponse() {
        }
        
        public GetDataByIDResponse(HUCEAdmin.sv1.GetDataByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan GetDataByIDResult;
        
        public GetDataByIDResponseBody() {
        }
        
        public GetDataByIDResponseBody(HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan GetDataByIDResult) {
            this.GetDataByIDResult = GetDataByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Search_PagingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search_Paging", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.Search_PagingRequestBody Body;
        
        public Search_PagingRequest() {
        }
        
        public Search_PagingRequest(HUCEAdmin.sv1.Search_PagingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Search_PagingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tk;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string search_val;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public HUCEAdmin.sv1.EnumDataType data_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int crr_page;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int page_size;
        
        public Search_PagingRequestBody() {
        }
        
        public Search_PagingRequestBody(string tk, string search_val, HUCEAdmin.sv1.EnumDataType data_type, int crr_page, int page_size) {
            this.tk = tk;
            this.search_val = search_val;
            this.data_type = data_type;
            this.crr_page = crr_page;
            this.page_size = page_size;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Search_PagingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search_PagingResponse", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.Search_PagingResponseBody Body;
        
        public Search_PagingResponse() {
        }
        
        public Search_PagingResponse(HUCEAdmin.sv1.Search_PagingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Search_PagingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HUCEAdmin.sv1.FunctResult_ettOfListOftbl_TaiKhoan Search_PagingResult;
        
        public Search_PagingResponseBody() {
        }
        
        public Search_PagingResponseBody(HUCEAdmin.sv1.FunctResult_ettOfListOftbl_TaiKhoan Search_PagingResult) {
            this.Search_PagingResult = Search_PagingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.CreateRequestBody Body;
        
        public CreateRequest() {
        }
        
        public CreateRequest(HUCEAdmin.sv1.CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tk;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public HUCEAdmin.sv1.tbl_TaiKhoan obj;
        
        public CreateRequestBody() {
        }
        
        public CreateRequestBody(string tk, HUCEAdmin.sv1.tbl_TaiKhoan obj) {
            this.tk = tk;
            this.obj = obj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.CreateResponseBody Body;
        
        public CreateResponse() {
        }
        
        public CreateResponse(HUCEAdmin.sv1.CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan CreateResult;
        
        public CreateResponseBody() {
        }
        
        public CreateResponseBody(HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan CreateResult) {
            this.CreateResult = CreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.EditRequestBody Body;
        
        public EditRequest() {
        }
        
        public EditRequest(HUCEAdmin.sv1.EditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tk;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public HUCEAdmin.sv1.tbl_TaiKhoan obj;
        
        public EditRequestBody() {
        }
        
        public EditRequestBody(string tk, HUCEAdmin.sv1.tbl_TaiKhoan obj) {
            this.tk = tk;
            this.obj = obj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditResponse", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.EditResponseBody Body;
        
        public EditResponse() {
        }
        
        public EditResponse(HUCEAdmin.sv1.EditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan EditResult;
        
        public EditResponseBody() {
        }
        
        public EditResponseBody(HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan EditResult) {
            this.EditResult = EditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(HUCEAdmin.sv1.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tk;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string tk, string id) {
            this.tk = tk;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public HUCEAdmin.sv1.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(HUCEAdmin.sv1.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HUCEAdmin.sv1.FunctResult_ettOfBoolean DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(HUCEAdmin.sv1.FunctResult_ettOfBoolean DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HUCEAdmin.sv1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HUCEAdmin.sv1.WebService1Soap>, HUCEAdmin.sv1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HUCEAdmin.sv1.LoginResponse HUCEAdmin.sv1.WebService1Soap.Login(HUCEAdmin.sv1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan Login(string tk, string mk) {
            HUCEAdmin.sv1.LoginRequest inValue = new HUCEAdmin.sv1.LoginRequest();
            inValue.Body = new HUCEAdmin.sv1.LoginRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.mk = mk;
            HUCEAdmin.sv1.LoginResponse retVal = ((HUCEAdmin.sv1.WebService1Soap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.LoginResponse> HUCEAdmin.sv1.WebService1Soap.LoginAsync(HUCEAdmin.sv1.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<HUCEAdmin.sv1.LoginResponse> LoginAsync(string tk, string mk) {
            HUCEAdmin.sv1.LoginRequest inValue = new HUCEAdmin.sv1.LoginRequest();
            inValue.Body = new HUCEAdmin.sv1.LoginRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.mk = mk;
            return ((HUCEAdmin.sv1.WebService1Soap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HUCEAdmin.sv1.LogoutResponse HUCEAdmin.sv1.WebService1Soap.Logout(HUCEAdmin.sv1.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan Logout(string tk) {
            HUCEAdmin.sv1.LogoutRequest inValue = new HUCEAdmin.sv1.LogoutRequest();
            inValue.Body = new HUCEAdmin.sv1.LogoutRequestBody();
            inValue.Body.tk = tk;
            HUCEAdmin.sv1.LogoutResponse retVal = ((HUCEAdmin.sv1.WebService1Soap)(this)).Logout(inValue);
            return retVal.Body.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.LogoutResponse> HUCEAdmin.sv1.WebService1Soap.LogoutAsync(HUCEAdmin.sv1.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<HUCEAdmin.sv1.LogoutResponse> LogoutAsync(string tk) {
            HUCEAdmin.sv1.LogoutRequest inValue = new HUCEAdmin.sv1.LogoutRequest();
            inValue.Body = new HUCEAdmin.sv1.LogoutRequestBody();
            inValue.Body.tk = tk;
            return ((HUCEAdmin.sv1.WebService1Soap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HUCEAdmin.sv1.GetDataResponse HUCEAdmin.sv1.WebService1Soap.GetData(HUCEAdmin.sv1.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public HUCEAdmin.sv1.FunctResult_ettOfListOftbl_TaiKhoan GetData(string tk) {
            HUCEAdmin.sv1.GetDataRequest inValue = new HUCEAdmin.sv1.GetDataRequest();
            inValue.Body = new HUCEAdmin.sv1.GetDataRequestBody();
            inValue.Body.tk = tk;
            HUCEAdmin.sv1.GetDataResponse retVal = ((HUCEAdmin.sv1.WebService1Soap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.GetDataResponse> HUCEAdmin.sv1.WebService1Soap.GetDataAsync(HUCEAdmin.sv1.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<HUCEAdmin.sv1.GetDataResponse> GetDataAsync(string tk) {
            HUCEAdmin.sv1.GetDataRequest inValue = new HUCEAdmin.sv1.GetDataRequest();
            inValue.Body = new HUCEAdmin.sv1.GetDataRequestBody();
            inValue.Body.tk = tk;
            return ((HUCEAdmin.sv1.WebService1Soap)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HUCEAdmin.sv1.GetDataByIDResponse HUCEAdmin.sv1.WebService1Soap.GetDataByID(HUCEAdmin.sv1.GetDataByIDRequest request) {
            return base.Channel.GetDataByID(request);
        }
        
        public HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan GetDataByID(string tk, string id) {
            HUCEAdmin.sv1.GetDataByIDRequest inValue = new HUCEAdmin.sv1.GetDataByIDRequest();
            inValue.Body = new HUCEAdmin.sv1.GetDataByIDRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.id = id;
            HUCEAdmin.sv1.GetDataByIDResponse retVal = ((HUCEAdmin.sv1.WebService1Soap)(this)).GetDataByID(inValue);
            return retVal.Body.GetDataByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.GetDataByIDResponse> HUCEAdmin.sv1.WebService1Soap.GetDataByIDAsync(HUCEAdmin.sv1.GetDataByIDRequest request) {
            return base.Channel.GetDataByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<HUCEAdmin.sv1.GetDataByIDResponse> GetDataByIDAsync(string tk, string id) {
            HUCEAdmin.sv1.GetDataByIDRequest inValue = new HUCEAdmin.sv1.GetDataByIDRequest();
            inValue.Body = new HUCEAdmin.sv1.GetDataByIDRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.id = id;
            return ((HUCEAdmin.sv1.WebService1Soap)(this)).GetDataByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HUCEAdmin.sv1.Search_PagingResponse HUCEAdmin.sv1.WebService1Soap.Search_Paging(HUCEAdmin.sv1.Search_PagingRequest request) {
            return base.Channel.Search_Paging(request);
        }
        
        public HUCEAdmin.sv1.FunctResult_ettOfListOftbl_TaiKhoan Search_Paging(string tk, string search_val, HUCEAdmin.sv1.EnumDataType data_type, int crr_page, int page_size) {
            HUCEAdmin.sv1.Search_PagingRequest inValue = new HUCEAdmin.sv1.Search_PagingRequest();
            inValue.Body = new HUCEAdmin.sv1.Search_PagingRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.search_val = search_val;
            inValue.Body.data_type = data_type;
            inValue.Body.crr_page = crr_page;
            inValue.Body.page_size = page_size;
            HUCEAdmin.sv1.Search_PagingResponse retVal = ((HUCEAdmin.sv1.WebService1Soap)(this)).Search_Paging(inValue);
            return retVal.Body.Search_PagingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.Search_PagingResponse> HUCEAdmin.sv1.WebService1Soap.Search_PagingAsync(HUCEAdmin.sv1.Search_PagingRequest request) {
            return base.Channel.Search_PagingAsync(request);
        }
        
        public System.Threading.Tasks.Task<HUCEAdmin.sv1.Search_PagingResponse> Search_PagingAsync(string tk, string search_val, HUCEAdmin.sv1.EnumDataType data_type, int crr_page, int page_size) {
            HUCEAdmin.sv1.Search_PagingRequest inValue = new HUCEAdmin.sv1.Search_PagingRequest();
            inValue.Body = new HUCEAdmin.sv1.Search_PagingRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.search_val = search_val;
            inValue.Body.data_type = data_type;
            inValue.Body.crr_page = crr_page;
            inValue.Body.page_size = page_size;
            return ((HUCEAdmin.sv1.WebService1Soap)(this)).Search_PagingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HUCEAdmin.sv1.CreateResponse HUCEAdmin.sv1.WebService1Soap.Create(HUCEAdmin.sv1.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan Create(string tk, HUCEAdmin.sv1.tbl_TaiKhoan obj) {
            HUCEAdmin.sv1.CreateRequest inValue = new HUCEAdmin.sv1.CreateRequest();
            inValue.Body = new HUCEAdmin.sv1.CreateRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.obj = obj;
            HUCEAdmin.sv1.CreateResponse retVal = ((HUCEAdmin.sv1.WebService1Soap)(this)).Create(inValue);
            return retVal.Body.CreateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.CreateResponse> HUCEAdmin.sv1.WebService1Soap.CreateAsync(HUCEAdmin.sv1.CreateRequest request) {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<HUCEAdmin.sv1.CreateResponse> CreateAsync(string tk, HUCEAdmin.sv1.tbl_TaiKhoan obj) {
            HUCEAdmin.sv1.CreateRequest inValue = new HUCEAdmin.sv1.CreateRequest();
            inValue.Body = new HUCEAdmin.sv1.CreateRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.obj = obj;
            return ((HUCEAdmin.sv1.WebService1Soap)(this)).CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HUCEAdmin.sv1.EditResponse HUCEAdmin.sv1.WebService1Soap.Edit(HUCEAdmin.sv1.EditRequest request) {
            return base.Channel.Edit(request);
        }
        
        public HUCEAdmin.sv1.FunctResult_ettOftbl_TaiKhoan Edit(string tk, HUCEAdmin.sv1.tbl_TaiKhoan obj) {
            HUCEAdmin.sv1.EditRequest inValue = new HUCEAdmin.sv1.EditRequest();
            inValue.Body = new HUCEAdmin.sv1.EditRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.obj = obj;
            HUCEAdmin.sv1.EditResponse retVal = ((HUCEAdmin.sv1.WebService1Soap)(this)).Edit(inValue);
            return retVal.Body.EditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.EditResponse> HUCEAdmin.sv1.WebService1Soap.EditAsync(HUCEAdmin.sv1.EditRequest request) {
            return base.Channel.EditAsync(request);
        }
        
        public System.Threading.Tasks.Task<HUCEAdmin.sv1.EditResponse> EditAsync(string tk, HUCEAdmin.sv1.tbl_TaiKhoan obj) {
            HUCEAdmin.sv1.EditRequest inValue = new HUCEAdmin.sv1.EditRequest();
            inValue.Body = new HUCEAdmin.sv1.EditRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.obj = obj;
            return ((HUCEAdmin.sv1.WebService1Soap)(this)).EditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HUCEAdmin.sv1.DeleteResponse HUCEAdmin.sv1.WebService1Soap.Delete(HUCEAdmin.sv1.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public HUCEAdmin.sv1.FunctResult_ettOfBoolean Delete(string tk, string id) {
            HUCEAdmin.sv1.DeleteRequest inValue = new HUCEAdmin.sv1.DeleteRequest();
            inValue.Body = new HUCEAdmin.sv1.DeleteRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.id = id;
            HUCEAdmin.sv1.DeleteResponse retVal = ((HUCEAdmin.sv1.WebService1Soap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HUCEAdmin.sv1.DeleteResponse> HUCEAdmin.sv1.WebService1Soap.DeleteAsync(HUCEAdmin.sv1.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<HUCEAdmin.sv1.DeleteResponse> DeleteAsync(string tk, string id) {
            HUCEAdmin.sv1.DeleteRequest inValue = new HUCEAdmin.sv1.DeleteRequest();
            inValue.Body = new HUCEAdmin.sv1.DeleteRequestBody();
            inValue.Body.tk = tk;
            inValue.Body.id = id;
            return ((HUCEAdmin.sv1.WebService1Soap)(this)).DeleteAsync(inValue);
        }
    }
}
